### ISSUE TITLE
Instruções de instalação local

### ISSUE THREAD

**Issue by PauloSilva92** [renatomarinho/GitScrum#1]
Poderia haver instruções de instalação localmente no README. Como instalar as dependências, rodar o app e etc.

**Comment by rafa-acioly** [comment]
A principio seria o básico Paulo,
```
composer update / install

-- Banco de dados --
1. Coloque as configurações no .env
2. rode - php artisan migrate
```

**Comment by PauloSilva92** [comment]
Sim eu sei. mas fica mais facil estar no README, até mesmo pra quem não tem muita experiencia com laravael/composer

**Comment by paulodealmeida** [comment]
Estou com dificuldade de instalação, se tivesse um passo-a-passo seria ótimo.

**Comment by renatomarinho** [comment]
@marcosrjjunior criou o setup inicial explicando como criar a github app. VERY WELL!!!

**Comment by wilianuhlmann** [comment]
Criado o github app é só eu clonar o projeto para a minha maquina em uma pasta com o laravel?

**Comment by marcosrjjunior** [comment]
O projeto já é laravel @wilianuhlmann, você clona ele inteiro, preenche o arquivo .env com as informações geradas pelo sua aplicação do Github, e outras informações como database. 

E prossiga a instalação do laravel
```
composer install
php artisan key:generate
php artisan migrate -s
```

**Comment by ale-php** [comment]
pesoal fiz isso e esta dando

The requested URL /auth/login was not found on this server.

não entendi o pq

**Comment by duard** [comment]
Seguindo estes passos, estou tendo este problema

```
> $ php artisan migrate                                                                                                                                                                   [±master ●]

In Connection.php line 664:

  could not find driver (SQL: select * from information_schema.tables where table_schema = planeja and table_name = migrations)


In PDOConnection.php line 47:

  could not find driver


In PDOConnection.php line 43:

  could not find driver

```

**Comment by renatomarinho** [comment]
@duard o mysql está instalado corretamente? os dados de acesso estão corretos?
