### ISSUE TITLE
Erro

### ISSUE THREAD

**Issue by wilianuhlmann** [renatomarinho/GitScrum#6]
Clonei o repositorio,
 rodei composer install
rodei key:generate
rodei migrate
Mas estou tendo esse erro nao entendo o porque
Warning: Unknown: failed to open stream: No such file or directory in Unknown on line 0

Fatal error: Unknown: Failed opening required 'C:\www\GitScrum/server.php' (include_path='.;c:\php\includes') in Unknown on line 0

**Comment by willianmano** [comment]
Deu permissão nas pastas storage e bootstrap?

**Comment by wilianuhlmann** [comment]
Sim, e estou usando windows

**Comment by willianmano** [comment]
Esse é o problema. Windows. rsrs (brincadeira)

Cara, tenta instalar com o docker. A vida fica bem mais fácil. Sei que seria mais agradável resolver esse problema no windows, mas faz tanto tempo que não uso o janelas que pelo menos eu não poderei te ajudar.

**Comment by wilianuhlmann** [comment]
Realente Windows é complicado, vou tentar pelo Bash no ubunto do windows e pelo docker valeu.
